### ISSUE TITLE
EC3D dataset clarification

### ISSUE THREAD

**Issue by cyprusad** [Jacoo-Zhao/3D-Pose-Based-Feedback-For-Physical-Exercises#1]
In your paper and in the video explaining the paper https://www.youtube.com/watch?v=W3kyyeHe0SI you mention the EC3D dataset, however, in the code it is a binary pickle file.

I saw a reference to your dataset in another paper on the FLAG3D dataset here https://openaccess.thecvf.com/content/CVPR2023/papers/Tang_FLAG3D_A_3D_Fitness_Activity_Dataset_With_Language_Instruction_CVPR_2023_paper.pdf

Would you be able to comment on the methodology of how the dataset was made? What are the sequences of exercise motions that are used? Also, which model is used for keypoint estimation of the EC3D dataset in your code before it is serialized into a  pickle file?

@Jacoo-Zhao

**Comment by Jacoo-Zhao** [comment]
We have three motion sequences: Squats; Lunge; and Planks, each of them is implemented by four different subjects. The videos were captured by 4 GoPro cameras placed in a ring around the subject, using a frame rate of 30 fps and a 1920 × 1080 image resolution. And keypoints are estimated by OpenPose (https://github.com/CMU-Perceptual-Computing-Lab/openpose).
