### ISSUE TITLE
Do it support multiviews?

### ISSUE THREAD

**Issue by YoungjaeDev** [Jacoo-Zhao/3D-Pose-Based-Feedback-For-Physical-Exercises#4]
Do you support 3D pose extraction for multiview cameras?

Also, looking at the github issue, there seems to be a problem with the execution, has it been resolved?

**Comment by YoungjaeDev** [comment]
I've read the paper, where is the code to make the 2D from each camera into 3D?

**Comment by Jacoo-Zhao** [comment]
> Do you support 3D pose extraction for multiview cameras?
> Also, looking at the github issue, there seems to be a problem with the execution, has it been resolved?

Sorry, it is not supported.
As the questioner didn't ask any further questions, I hope all is well.


>I've read the paper, where is the code to make the 2D from each camera into 3D?

This code is private and is not the main contribution of our paper. Our focus is on pose correction.
